21:26:12.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:26:12.020 - My_app - INFO - Current user is user (main.py:167)
21:26:16.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:16.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:17.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:17.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:18.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:18.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:19.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:22.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:28.020 - My_app - INFO - user is log out (main.py:130)
21:26:31.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:26:31.020 - My_app - INFO - Current user is user (main.py:167)
21:26:32.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:32.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:33.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:33.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:34.020 - My_app - ERROR - Dialogue window already opened (main.py:174)
21:26:35.020 - My_app - INFO - user is log out (main.py:130)
21:26:41.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:26:41.020 - My_app - INFO - Current user is user (main.py:167)
21:26:42.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:42.020 - My_app - ERROR - Dialogue window already opened (main.py:180)
21:26:44.020 - My_app - INFO - user is log out (main.py:130)
21:27:37.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:27:37.020 - My_app - INFO - Current user is user (main.py:167)
21:27:39.020 - My_app - INFO - user is log out (main.py:130)
21:27:42.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:27:42.020 - My_app - INFO - Current user is user (main.py:167)
21:27:43.020 - My_app - INFO - user is log out (main.py:130)
21:27:52.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:27:52.020 - My_app - INFO - Current user is user (main.py:167)
21:30:26.020 - My_app - INFO - user is log out (main.py:130)
21:57:00.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:57:00.020 - My_app - INFO - Current user is user (main.py:179)
21:57:08.020 - My_app - INFO - user is log out (main.py:142)
21:58:13.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
21:58:13.020 - My_app - INFO - Current user is user (main.py:180)
21:58:31.020 - My_app - ERROR - 1142 (42000): INSERT command denied to user 'user'@'localhost' for table 'Orders' (main.py:89)
21:58:31.020 - My_app - INFO - Order added in table (main.py:259)
21:58:45.020 - My_app - INFO - user is log out (main.py:143)
22:02:16.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
22:02:16.020 - My_app - INFO - Current user is user (main.py:180)
22:02:20.020 - My_app - ERROR - 1216 (23000): Cannot add or update a child row: a foreign key constraint fails (main.py:89)
22:02:20.020 - My_app - INFO - Order added in table (main.py:259)
22:02:43.020 - My_app - INFO - user is log out (main.py:143)
22:48:47.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
22:48:47.020 - My_app - INFO - Current user is user (main.py:180)
22:57:20.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
22:57:20.020 - My_app - INFO - Current user is user (main.py:180)
22:57:46.020 - My_app - INFO - Order added in table (main.py:259)
22:58:55.020 - My_app - INFO - Order added in table (main.py:259)
23:04:53.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:04:53.020 - My_app - INFO - Current user is user (main.py:180)
23:04:59.020 - My_app - ERROR - Error checking id (main.py:27)
23:04:59.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:05:23.020 - My_app - INFO - user is log out (main.py:143)
23:05:50.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:05:50.020 - My_app - INFO - Current user is user (main.py:180)
23:05:55.020 - My_app - ERROR - Error checking id (main.py:27)
23:05:55.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:06:14.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:06:14.020 - My_app - INFO - Current user is user (main.py:180)
23:06:17.020 - My_app - ERROR - Error checking id (main.py:27)
23:06:17.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:06:35.020 - My_app - INFO - user is log out (main.py:143)
23:09:55.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:09:55.020 - My_app - INFO - Current user is user (main.py:180)
23:09:59.020 - My_app - ERROR - Error checking id (main.py:27)
23:09:59.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:11:14.020 - My_app - ERROR - Error checking id (main.py:27)
23:11:14.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:11:14.020 - My_app - ERROR - Error checking id (main.py:27)
23:11:14.020 - My_app - ERROR - Voyage id entered is invalid (main.py:245)
23:18:02.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:18:02.020 - My_app - INFO - Current user is user (main.py:180)
23:18:06.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:06.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:10.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:10.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:12.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:12.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:13.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:13.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:44.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:18:44.020 - My_app - INFO - Current user is user (main.py:180)
23:18:47.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:47.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:49.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:49.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:52.020 - My_app - ERROR - Error checking id (main.py:27)
23:18:52.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:18:56.020 - My_app - INFO - user is log out (main.py:143)
23:20:46.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:20:46.020 - My_app - INFO - Current user is user (main.py:180)
23:20:50.020 - My_app - ERROR - Error checking id (main.py:27)
23:20:50.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:20:51.020 - My_app - ERROR - Error checking id (main.py:27)
23:20:51.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:21:01.020 - My_app - ERROR - Error checking id (main.py:27)
23:21:01.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:21:06.020 - My_app - ERROR - Error checking id (main.py:27)
23:21:06.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:21:08.020 - My_app - ERROR - Error checking id (main.py:27)
23:21:08.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:21:17.020 - My_app - INFO - user is log out (main.py:143)
23:22:55.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:22:55.020 - My_app - INFO - Current user is user (main.py:180)
23:23:13.020 - My_app - ERROR - Error checking id (main.py:27)
23:23:13.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:23:16.020 - My_app - ERROR - Error checking id (main.py:27)
23:23:16.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:23:23.020 - My_app - INFO - user is log out (main.py:143)
23:23:44.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:23:44.020 - My_app - INFO - Current user is user (main.py:180)
23:23:48.020 - My_app - ERROR - Error checking id (main.py:27)
23:23:48.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:23:50.020 - My_app - ERROR - Error checking id (main.py:27)
23:23:50.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:23:52.020 - My_app - INFO - user is log out (main.py:143)
23:24:39.020 - My_app - ERROR - Not a Phone number entered (main.py:132)
23:24:44.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:24:44.020 - My_app - INFO - Current user is user (main.py:180)
23:24:49.020 - My_app - ERROR - Error checking id (main.py:27)
23:24:49.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:24:50.020 - My_app - ERROR - Error checking id (main.py:27)
23:24:50.020 - My_app - ERROR - Voyage id entered is invalid (main.py:247)
23:25:06.020 - My_app - INFO - user is log out (main.py:143)
23:27:48.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:27:48.020 - My_app - INFO - Current user is user (main.py:180)
23:27:52.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:52.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:53.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:53.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:55.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:55.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:56.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:56.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:57.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:57.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:57.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:57.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:27:58.020 - My_app - ERROR - Error checking id (main.py:27)
23:27:58.020 - My_app - ERROR - Voyage id entered is invalid (main.py:246)
23:28:05.020 - My_app - INFO - user is log out (main.py:143)
23:33:25.020 - My_app - INFO - Connected to MySQL by user (main.py:67)
23:33:25.020 - My_app - INFO - Current user is user (main.py:180)
23:33:30.020 - My_app - INFO - user is log out (main.py:143)
00:16:07.021 - My_app - ERROR - Not a Phone number entered (main.py:148)
00:16:20.021 - My_app - DEBUG - None (main.py:42)
00:16:20.021 - My_app - ERROR - Invalid phone number (main.py:81)
00:16:32.021 - My_app - DEBUG - None (main.py:42)
00:16:32.021 - My_app - ERROR - Invalid phone number (main.py:81)
00:17:57.021 - My_app - DEBUG - (1,) (main.py:42)
00:18:05.021 - My_app - INFO - Connected to MySQL by user (main.py:79)
00:18:05.021 - My_app - INFO - Current user is user (main.py:194)
00:21:02.021 - My_app - ERROR - Not a Phone number entered (main.py:150)
00:21:09.021 - My_app - DEBUG - Number check returned: None (main.py:42)
00:21:09.021 - My_app - INFO - Connected to MySQL by user (main.py:81)
00:21:09.021 - My_app - INFO - Current user is user (main.py:196)
00:27:21.021 - My_app - ERROR - Not a Phone number entered (main.py:152)
00:27:25.021 - My_app - ERROR - Not a Phone number entered (main.py:152)
00:27:41.021 - My_app - ERROR - Error connecting to MySQL (main.py:88)
00:27:58.021 - My_app - DEBUG - Number check returned: None (main.py:42)
00:27:58.021 - My_app - ERROR - Invalid phone number (main.py:85)
00:29:11.021 - My_app - ERROR - Not a Phone number entered (main.py:152)
00:29:15.021 - My_app - ERROR - Not a Phone number entered (main.py:152)
00:29:38.021 - My_app - ERROR - Not a Phone number entered (main.py:152)
00:29:42.021 - My_app - ERROR - Not a Phone number entered (main.py:152)
00:30:08.021 - My_app - DEBUG - Number check returned: None (main.py:42)
00:30:08.021 - My_app - ERROR - Invalid phone number (main.py:85)
00:30:38.021 - My_app - DEBUG - Number check returned: None (main.py:42)
00:30:38.021 - My_app - ERROR - Invalid phone number (main.py:85)
00:30:39.021 - My_app - DEBUG - Number check returned: None (main.py:42)
00:30:39.021 - My_app - ERROR - Invalid phone number (main.py:85)
00:30:45.021 - My_app - DEBUG - Number check returned: (1,) (main.py:42)
00:30:45.021 - My_app - INFO - Connected to MySQL by user (main.py:83)
00:30:45.021 - My_app - INFO - Current user is user (main.py:198)
00:30:57.021 - My_app - INFO - user is log out (main.py:163)
00:31:02.021 - My_app - ERROR - Not a Phone number entered (main.py:152)
00:31:04.021 - My_app - ERROR - Not a Phone number entered (main.py:152)
00:31:12.021 - My_app - DEBUG - Number check returned: None (main.py:42)
00:31:12.021 - My_app - ERROR - Invalid phone number (main.py:85)
00:31:13.021 - My_app - DEBUG - Number check returned: None (main.py:42)
00:31:13.021 - My_app - ERROR - Invalid phone number (main.py:85)
00:31:14.021 - My_app - DEBUG - Number check returned: None (main.py:42)
00:31:14.021 - My_app - ERROR - Invalid phone number (main.py:85)
00:40:36.021 - My_app - INFO - Connected to MySQL by admin (main.py:71)
00:40:36.021 - My_app - INFO - Current user is admin (main.py:198)
00:54:24.021 - My_app - DEBUG - Number check returned: (1,) (main.py:42)
00:54:24.021 - My_app - INFO - Connected to MySQL by user (main.py:83)
00:54:24.021 - My_app - INFO - Current user is user (main.py:435)
01:38:04.021 - My_app - DEBUG - Number check returned: (1,) (main.py:42)
01:38:04.021 - My_app - INFO - Connected to MySQL by user (main.py:83)
01:39:26.021 - My_app - DEBUG - Number check returned: (1,) (main.py:42)
01:39:26.021 - My_app - INFO - Connected to MySQL by user (main.py:83)
01:41:04.021 - My_app - DEBUG - Number check returned: (1,) (main.py:42)
01:41:04.021 - My_app - INFO - Connected to MySQL by user (main.py:83)
01:41:04.021 - My_app - INFO - Current user is user (main.py:271)
01:41:26.021 - My_app - ERROR - 1216 (23000): Cannot add or update a child row: a foreign key constraint fails (main.py:111)
01:41:26.021 - My_app - ERROR - Failed to add order (main.py:364)
01:42:14.021 - My_app - INFO - Order added in table (main.py:361)
01:42:52.021 - My_app - ERROR - Dialogue window already opened (main.py:285)
01:43:05.021 - My_app - ERROR - Could not process parameters: type(<class '__main__.MySQLConnector'>), it must be of type list, tuple or dict (main.py:124)
01:43:05.021 - My_app - ERROR - Failed to delete order (main.py:438)
01:44:47.021 - My_app - DEBUG - Number check returned: (1,) (main.py:42)
01:44:47.021 - My_app - INFO - Connected to MySQL by user (main.py:83)
01:44:47.021 - My_app - INFO - Current user is user (main.py:271)
01:46:45.021 - DEBUG - Number check returned: (1,) (main.py:42)
01:46:45.021 - INFO - Connected to MySQL by user (main.py:83)
01:46:45.021 - INFO - Current user is user (main.py:271)
01:47:55.021 - DEBUG - Number check returned: (1,) (main.py:42)
01:47:55.021 - INFO - Connected to MySQL by user (main.py:83)
01:47:55.021 - INFO - Current user is user (main.py:271)
01:48:12.021 - INFO - user is log out (main.py:185)
01:49:31.021 - DEBUG - Number check returned: (1,) (main.py:42)
01:49:31.021 - INFO - Connected to MySQL by user (main.py:83)
01:49:31.021 - INFO - Current user is user (main.py:271)
01:50:06.021 - DEBUG - Number check returned: (1,) (main.py:42)
01:50:06.021 - INFO - Connected to MySQL by user (main.py:83)
01:50:06.021 - INFO - Current user is user (main.py:271)
01:50:28.021 - DEBUG - Number check returned: (1,) (main.py:42)
01:50:28.021 - INFO - Connected to MySQL by user (main.py:83)
01:50:28.021 - INFO - Current user is user (main.py:271)
01:51:12.021 - DEBUG - Number check returned: (1,) (main.py:42)
01:51:12.021 - INFO - Connected to MySQL by user (main.py:83)
01:51:12.021 - INFO - Current user is user (main.py:271)
01:54:23.021 - DEBUG - Number check returned: (1,) (main.py:42)
01:54:23.021 - INFO - Connected to MySQL by user (main.py:83)
01:54:23.021 - INFO - Current user is user (main.py:271)
01:54:25.021 - INFO - Order deleted from table (main.py:435)
01:56:03.021 - DEBUG - Number check returned: (1,) (main.py:42)
01:56:03.021 - INFO - Connected to MySQL by user (main.py:83)
01:56:03.021 - INFO - Current user is user (main.py:271)
01:56:09.021 - INFO - Order added in table (main.py:361)
01:56:12.021 - INFO - Order added in table (main.py:361)
01:56:15.021 - INFO - Order added in table (main.py:361)
02:00:11.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:00:11.021 - INFO - Connected to MySQL by user (main.py:83)
02:00:11.021 - INFO - Current user is user (main.py:271)
02:01:07.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:01:07.021 - INFO - Connected to MySQL by user (main.py:83)
02:01:07.021 - INFO - Current user is user (main.py:271)
02:01:26.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:01:26.021 - INFO - Connected to MySQL by user (main.py:83)
02:01:26.021 - INFO - Current user is user (main.py:271)
02:01:51.021 - ERROR - 1216 (23000): Cannot add or update a child row: a foreign key constraint fails (main.py:111)
02:01:51.021 - ERROR - Failed to add order (main.py:357)
02:02:34.021 - INFO - Order added in table (main.py:354)
02:03:14.021 - ERROR - Failed to delete order (main.py:431)
02:03:22.021 - INFO - user is log out (main.py:185)
02:04:04.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:04:04.021 - INFO - Connected to MySQL by user (main.py:83)
02:04:04.021 - INFO - Current user is user (main.py:271)
02:04:44.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:04:44.021 - INFO - Connected to MySQL by user (main.py:83)
02:04:44.021 - INFO - Current user is user (main.py:271)
02:04:50.021 - INFO - user is log out (main.py:185)
02:05:01.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:05:01.021 - INFO - Connected to MySQL by user (main.py:83)
02:05:01.021 - INFO - Current user is user (main.py:271)
02:05:39.021 - INFO - Order deleted from table (main.py:428)
02:06:35.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:06:35.021 - INFO - Connected to MySQL by user (main.py:83)
02:06:35.021 - INFO - Current user is user (main.py:271)
02:06:39.021 - ERROR - Failed to delete order (main.py:431)
02:06:43.021 - ERROR - Failed to delete order (main.py:431)
02:06:45.021 - ERROR - Failed to delete order (main.py:431)
02:07:50.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:07:50.021 - INFO - Connected to MySQL by user (main.py:83)
02:07:50.021 - INFO - Current user is user (main.py:271)
02:14:07.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:14:07.021 - INFO - Connected to MySQL by user (main.py:83)
02:14:07.021 - INFO - Current user is user (main.py:271)
02:14:10.021 - INFO - Order deleted from table (main.py:428)
02:14:19.021 - ERROR - Failed to delete order (main.py:431)
02:29:16.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:29:16.021 - INFO - Connected to MySQL by user (main.py:83)
02:29:16.021 - INFO - Current user is user (main.py:271)
02:31:12.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:31:12.021 - INFO - Connected to MySQL by user (main.py:83)
02:31:42.021 - ERROR - Not a Phone number entered (main.py:174)
02:31:46.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:31:46.021 - INFO - Connected to MySQL by user (main.py:83)
02:31:46.021 - INFO - Current user is user (main.py:280)
02:32:07.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:32:07.021 - INFO - Connected to MySQL by user (main.py:83)
02:32:07.021 - INFO - Current user is user (main.py:280)
02:32:19.021 - ERROR - Dialogue window already opened (main.py:287)
02:32:19.021 - ERROR - Dialogue window already opened (main.py:287)
02:32:19.021 - ERROR - Dialogue window already opened (main.py:287)
02:32:20.021 - ERROR - Dialogue window already opened (main.py:294)
02:32:20.021 - ERROR - Dialogue window already opened (main.py:294)
02:32:20.021 - ERROR - Dialogue window already opened (main.py:294)
02:32:21.021 - ERROR - Dialogue window already opened (main.py:294)
02:32:21.021 - ERROR - Dialogue window already opened (main.py:294)
02:32:22.021 - ERROR - Dialogue window already opened (main.py:301)
02:32:22.021 - ERROR - Dialogue window already opened (main.py:301)
02:32:22.021 - ERROR - Dialogue window already opened (main.py:294)
02:32:22.021 - ERROR - Dialogue window already opened (main.py:294)
02:32:22.021 - ERROR - Dialogue window already opened (main.py:287)
02:32:37.021 - INFO - user is log out (main.py:185)
02:32:40.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:32:40.021 - INFO - Connected to MySQL by user (main.py:83)
02:32:40.021 - INFO - Current user is user (main.py:280)
02:32:44.021 - INFO - user is log out (main.py:185)
02:32:45.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:32:45.021 - INFO - Connected to MySQL by user (main.py:83)
02:32:45.021 - INFO - Current user is user (main.py:280)
02:32:47.021 - INFO - user is log out (main.py:185)
02:32:50.021 - INFO - Connected to MySQL by admin (main.py:71)
02:32:50.021 - INFO - Current user is admin (main.py:280)
02:33:15.021 - INFO - Connected to MySQL by admin (main.py:71)
02:33:15.021 - INFO - Current user is admin (main.py:280)
02:34:42.021 - INFO - Connected to MySQL by admin (main.py:71)
02:34:42.021 - INFO - Current user is admin (main.py:222)
02:35:04.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:35:04.021 - INFO - Connected to MySQL by user (main.py:83)
02:35:04.021 - INFO - Current user is user (main.py:283)
02:35:07.021 - INFO - user is log out (main.py:188)
02:35:12.021 - INFO - Connected to MySQL by admin (main.py:71)
02:35:12.021 - INFO - Current user is admin (main.py:222)
02:36:56.021 - INFO - Connected to MySQL by admin (main.py:71)
02:36:56.021 - INFO - Current user is admin (main.py:231)
02:36:59.021 - INFO - admin is log out (main.py:188)
02:37:05.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:37:05.021 - INFO - Connected to MySQL by user (main.py:83)
02:37:05.021 - INFO - Current user is user (main.py:297)
02:37:12.021 - ERROR - Dialogue window already opened (main.py:304)
02:37:12.021 - ERROR - Dialogue window already opened (main.py:304)
02:37:12.021 - ERROR - Dialogue window already opened (main.py:304)
02:37:12.021 - ERROR - Dialogue window already opened (main.py:304)
02:37:13.021 - INFO - user is log out (main.py:188)
02:37:17.021 - INFO - Connected to MySQL by admin (main.py:71)
02:37:17.021 - INFO - Current user is admin (main.py:231)
02:37:28.021 - INFO - admin is log out (main.py:188)
02:37:31.021 - INFO - Connected to MySQL by admin (main.py:71)
02:37:31.021 - INFO - Current user is admin (main.py:231)
02:37:43.021 - INFO - Connected to MySQL by admin (main.py:71)
02:37:43.021 - INFO - Current user is admin (main.py:231)
02:37:45.021 - INFO - admin is log out (main.py:188)
02:37:46.021 - INFO - Connected to MySQL by admin (main.py:71)
02:37:46.021 - INFO - Current user is admin (main.py:231)
02:37:47.021 - INFO - admin is log out (main.py:188)
02:37:48.021 - INFO - Connected to MySQL by admin (main.py:71)
02:37:48.021 - INFO - Current user is admin (main.py:231)
02:37:50.021 - INFO - admin is log out (main.py:188)
02:37:51.021 - INFO - Connected to MySQL by admin (main.py:71)
02:37:51.021 - INFO - Current user is admin (main.py:231)
02:37:53.021 - INFO - admin is log out (main.py:188)
02:38:03.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:38:03.021 - INFO - Connected to MySQL by user (main.py:83)
02:38:03.021 - INFO - Current user is user (main.py:297)
02:38:05.021 - INFO - user is log out (main.py:188)
02:38:06.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:38:06.021 - INFO - Connected to MySQL by user (main.py:83)
02:38:06.021 - INFO - Current user is user (main.py:297)
02:38:08.021 - INFO - user is log out (main.py:188)
02:38:08.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:38:08.021 - INFO - Connected to MySQL by user (main.py:83)
02:38:08.021 - INFO - Current user is user (main.py:297)
02:38:10.021 - INFO - user is log out (main.py:188)
02:38:11.021 - DEBUG - Number check returned: (1,) (main.py:42)
02:38:11.021 - INFO - Connected to MySQL by user (main.py:83)
02:38:11.021 - INFO - Current user is user (main.py:297)
02:38:12.021 - INFO - user is log out (main.py:188)
02:38:16.021 - INFO - Connected to MySQL by admin (main.py:71)
02:38:16.021 - INFO - Current user is admin (main.py:231)
02:38:17.021 - INFO - admin is log out (main.py:188)
02:38:18.021 - INFO - Connected to MySQL by admin (main.py:71)
02:38:18.021 - INFO - Current user is admin (main.py:231)
02:38:20.021 - INFO - admin is log out (main.py:188)
03:08:04.021 - DEBUG - Number check returned: (1,) (main.py:20)
03:08:04.021 - INFO - Connected to MySQL by user (main.py:83)
03:08:04.021 - INFO - Current user is user (main.py:309)
03:08:42.021 - DEBUG - Number check returned: (1,) (main.py:20)
03:08:42.021 - INFO - Connected to MySQL by user (main.py:83)
03:08:42.021 - INFO - Current user is user (main.py:309)
03:08:43.021 - ERROR - Error get orders data from database (main.py:146)
03:08:51.021 - DEBUG - Number check returned: (1,) (main.py:20)
03:08:51.021 - INFO - Connected to MySQL by user (main.py:83)
03:08:51.021 - INFO - Current user is user (main.py:309)
03:08:54.021 - ERROR - Error get orders data from database (main.py:146)
03:16:03.021 - DEBUG - Number check returned: (1,) (main.py:20)
03:16:03.021 - INFO - Connected to MySQL by user (main.py:83)
03:16:03.021 - INFO - Current user is user (main.py:312)
03:16:05.021 - ERROR - Error get orders data from database (main.py:146)
03:16:19.021 - DEBUG - Number check returned: (1,) (main.py:20)
03:16:19.021 - INFO - Connected to MySQL by user (main.py:83)
03:16:19.021 - INFO - Current user is user (main.py:312)
03:16:26.021 - ERROR - Error get orders data from database (main.py:146)
03:16:53.021 - DEBUG - Number check returned: (1,) (main.py:20)
03:16:53.021 - INFO - Connected to MySQL by user (main.py:83)
03:16:53.021 - INFO - Current user is user (main.py:312)
03:17:24.021 - DEBUG - Number check returned: (1,) (main.py:20)
03:17:24.021 - INFO - Connected to MySQL by user (main.py:83)
03:17:24.021 - INFO - Current user is user (main.py:312)
03:17:58.021 - DEBUG - Number check returned: (1,) (main.py:20)
03:17:58.021 - INFO - Connected to MySQL by user (main.py:83)
03:17:58.021 - INFO - Current user is user (main.py:312)
03:18:55.021 - DEBUG - Number check returned: (1,) (main.py:20)
03:18:55.021 - INFO - Connected to MySQL by user (main.py:83)
03:18:55.021 - INFO - Current user is user (main.py:312)
03:22:51.021 - DEBUG - Number check returned: (1,) (main.py:20)
03:22:51.021 - INFO - Connected to MySQL by user (main.py:83)
03:22:51.021 - INFO - Current user is user (main.py:312)
03:22:56.021 - INFO - Order added in table (main.py:402)
03:22:57.021 - INFO - Order added in table (main.py:402)
03:23:00.021 - INFO - Order added in table (main.py:402)
03:23:02.021 - INFO - Order added in table (main.py:402)
03:23:03.021 - INFO - Order added in table (main.py:402)
03:23:05.021 - INFO - Order added in table (main.py:402)
03:23:35.021 - ERROR - Dialogue window already opened (main.py:319)
03:23:36.021 - ERROR - Dialogue window already opened (main.py:319)
03:24:02.021 - INFO - Order deleted from table (main.py:476)
03:24:21.021 - INFO - Order added in table (main.py:402)
03:24:21.021 - INFO - Order added in table (main.py:402)
03:24:21.021 - INFO - Order added in table (main.py:402)
03:24:21.021 - INFO - Order added in table (main.py:402)
03:24:21.021 - INFO - Order added in table (main.py:402)
03:24:22.021 - INFO - Order added in table (main.py:402)
03:24:22.021 - INFO - Order added in table (main.py:402)
03:24:22.021 - INFO - Order added in table (main.py:402)
03:24:22.021 - INFO - Order added in table (main.py:402)
03:24:22.021 - INFO - Order added in table (main.py:402)
03:24:22.021 - INFO - Order added in table (main.py:402)
03:24:23.021 - INFO - Order added in table (main.py:402)
03:24:23.021 - INFO - Order added in table (main.py:402)
03:24:23.021 - INFO - Order added in table (main.py:402)
03:24:23.021 - INFO - Order added in table (main.py:402)
03:24:23.021 - INFO - Order added in table (main.py:402)
03:24:24.021 - INFO - Order added in table (main.py:402)
03:24:24.021 - INFO - Order added in table (main.py:402)
03:24:24.021 - INFO - Order added in table (main.py:402)
03:24:24.021 - INFO - Order added in table (main.py:402)
03:24:24.021 - INFO - Order added in table (main.py:402)
03:24:24.021 - INFO - Order added in table (main.py:402)
03:24:25.021 - INFO - Order added in table (main.py:402)
03:24:25.021 - INFO - Order added in table (main.py:402)
03:24:25.021 - INFO - Order added in table (main.py:402)
03:24:25.021 - INFO - Order added in table (main.py:402)
03:24:25.021 - INFO - Order added in table (main.py:402)
03:24:26.021 - INFO - Order added in table (main.py:402)
03:24:26.021 - INFO - Order added in table (main.py:402)
03:24:26.021 - INFO - Order added in table (main.py:402)
03:24:26.021 - INFO - Order added in table (main.py:402)
03:24:26.021 - INFO - Order added in table (main.py:402)
03:24:26.021 - INFO - Order added in table (main.py:402)
03:24:27.021 - INFO - Order added in table (main.py:402)
04:02:55.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:02:55.021 - INFO - Connected to MySQL by user (main.py:83)
04:02:55.021 - INFO - Current user is user (main.py:312)
04:03:07.021 - INFO - user is log out (main.py:201)
04:09:37.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:09:37.021 - INFO - Connected to MySQL by user (main.py:83)
04:09:37.021 - INFO - Current user is user (main.py:336)
04:10:00.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:10:00.021 - INFO - Connected to MySQL by user (main.py:83)
04:10:00.021 - INFO - Current user is user (main.py:336)
04:10:15.021 - INFO - user is log out (main.py:216)
04:18:20.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:18:20.021 - INFO - Connected to MySQL by user (main.py:83)
04:18:49.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:18:49.021 - INFO - Connected to MySQL by user (main.py:83)
04:18:49.021 - INFO - Current user is user (main.py:359)
04:19:21.021 - INFO - user is log out (main.py:230)
04:19:35.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:19:35.021 - INFO - Connected to MySQL by user (main.py:83)
04:19:35.021 - INFO - Current user is user (main.py:359)
04:19:47.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:19:47.021 - INFO - Connected to MySQL by user (main.py:83)
04:19:47.021 - INFO - Current user is user (main.py:359)
04:21:10.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:21:10.021 - INFO - Connected to MySQL by user (main.py:83)
04:21:10.021 - INFO - Current user is user (main.py:359)
04:21:11.021 - INFO - user is log out (main.py:230)
04:21:13.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:21:13.021 - INFO - Connected to MySQL by user (main.py:83)
04:21:13.021 - INFO - Current user is user (main.py:359)
04:21:17.021 - INFO - user is log out (main.py:230)
04:21:18.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:21:18.021 - INFO - Connected to MySQL by user (main.py:83)
04:21:18.021 - INFO - Current user is user (main.py:359)
04:21:22.021 - INFO - user is log out (main.py:230)
04:21:28.021 - INFO - Connected to MySQL by admin (main.py:71)
04:21:28.021 - INFO - Current user is admin (main.py:273)
04:26:04.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:26:05.021 - INFO - Connected to MySQL by user (main.py:83)
04:26:05.021 - INFO - Current user is user (main.py:383)
04:26:07.021 - INFO - user is log out (main.py:244)
04:26:38.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:26:38.021 - INFO - Connected to MySQL by user (main.py:83)
04:26:38.021 - INFO - Current user is user (main.py:383)
04:26:42.021 - INFO - user is log out (main.py:244)
04:27:16.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:27:16.021 - INFO - Connected to MySQL by user (main.py:83)
04:27:16.021 - INFO - Current user is user (main.py:383)
04:27:27.021 - INFO - user is log out (main.py:244)
04:28:28.021 - DEBUG - Number check returned: (1,) (main.py:20)
04:28:28.021 - INFO - Connected to MySQL by user (main.py:83)
04:28:28.021 - INFO - Current user is user (main.py:383)
04:28:40.021 - ERROR - Dialogue window already opened (main.py:416)
04:28:40.021 - ERROR - Dialogue window already opened (main.py:416)
04:28:40.021 - ERROR - Dialogue window already opened (main.py:416)
04:28:41.021 - ERROR - Dialogue window already opened (main.py:422)
04:28:41.021 - ERROR - Dialogue window already opened (main.py:422)
04:28:41.021 - ERROR - Dialogue window already opened (main.py:422)
04:28:47.021 - ERROR - Dialogue window already opened (main.py:410)
04:28:47.021 - ERROR - Dialogue window already opened (main.py:410)
04:28:47.021 - ERROR - Dialogue window already opened (main.py:410)
04:28:48.021 - ERROR - Dialogue window already opened (main.py:416)
04:28:48.021 - ERROR - Dialogue window already opened (main.py:416)
04:28:48.021 - ERROR - Dialogue window already opened (main.py:416)
04:28:49.021 - ERROR - Dialogue window already opened (main.py:404)
04:28:49.021 - ERROR - Dialogue window already opened (main.py:404)
04:28:50.021 - ERROR - Dialogue window already opened (main.py:397)
04:28:50.021 - ERROR - Dialogue window already opened (main.py:397)
04:28:51.021 - ERROR - Dialogue window already opened (main.py:390)
04:28:51.021 - ERROR - Dialogue window already opened (main.py:390)
04:28:58.021 - ERROR - Dialogue window already opened (main.py:416)
04:29:04.021 - ERROR - Dialogue window already opened (main.py:422)
04:29:05.021 - ERROR - Dialogue window already opened (main.py:422)
12:21:40.021 - DEBUG - Number check returned: (1,) (main.py:20)
12:21:40.021 - INFO - Connected to MySQL by user (main.py:83)
12:21:40.021 - INFO - Current user is user (main.py:407)
12:21:52.021 - INFO - user is log out (main.py:268)
12:21:56.021 - INFO - Connected to MySQL by admin (main.py:71)
12:21:56.021 - INFO - Current user is admin (main.py:311)
12:21:59.021 - INFO - admin is log out (main.py:268)
12:22:00.021 - INFO - Connected to MySQL by admin (main.py:71)
12:22:00.021 - INFO - Current user is admin (main.py:311)
12:22:05.021 - INFO - admin is log out (main.py:268)
13:25:51.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:25:51.021 - INFO - Connected to MySQL by user (main.py:83)
13:25:51.021 - INFO - Current user is user (main.py:407)
13:25:56.021 - ERROR - Dialogue window already opened (main.py:428)
13:25:57.021 - ERROR - Dialogue window already opened (main.py:428)
13:25:57.021 - ERROR - Dialogue window already opened (main.py:434)
13:25:57.021 - ERROR - Dialogue window already opened (main.py:434)
13:25:57.021 - ERROR - Dialogue window already opened (main.py:440)
13:25:58.021 - ERROR - Dialogue window already opened (main.py:446)
13:25:58.021 - ERROR - Dialogue window already opened (main.py:421)
13:25:58.021 - ERROR - Dialogue window already opened (main.py:421)
13:25:58.021 - ERROR - Dialogue window already opened (main.py:414)
13:26:09.021 - INFO - user is log out (main.py:268)
13:26:33.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:26:33.021 - INFO - Connected to MySQL by user (main.py:83)
13:26:33.021 - INFO - Current user is user (main.py:407)
13:26:43.021 - INFO - user is log out (main.py:268)
13:26:56.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:26:56.021 - INFO - Connected to MySQL by user (main.py:83)
13:26:56.021 - INFO - Current user is user (main.py:407)
13:27:00.021 - INFO - user is log out (main.py:268)
13:27:14.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:27:14.021 - INFO - Connected to MySQL by user (main.py:83)
13:27:14.021 - INFO - Current user is user (main.py:407)
13:27:17.021 - INFO - user is log out (main.py:268)
13:27:25.021 - ERROR - Not a Phone number entered (main.py:254)
13:27:25.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:27:25.021 - INFO - Connected to MySQL by user (main.py:83)
13:27:25.021 - INFO - Current user is user (main.py:407)
13:27:28.021 - INFO - user is log out (main.py:268)
13:27:35.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:27:35.021 - INFO - Connected to MySQL by user (main.py:83)
13:27:35.021 - INFO - Current user is user (main.py:407)
13:27:38.021 - INFO - user is log out (main.py:268)
13:27:47.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:27:47.021 - INFO - Connected to MySQL by user (main.py:83)
13:27:47.021 - INFO - Current user is user (main.py:407)
13:27:50.021 - INFO - user is log out (main.py:268)
13:27:55.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:27:55.021 - INFO - Connected to MySQL by user (main.py:83)
13:27:55.021 - INFO - Current user is user (main.py:407)
13:27:58.021 - INFO - user is log out (main.py:268)
13:28:03.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:28:03.021 - INFO - Connected to MySQL by user (main.py:83)
13:28:03.021 - INFO - Current user is user (main.py:407)
13:28:07.021 - INFO - user is log out (main.py:268)
13:28:12.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:28:12.021 - INFO - Connected to MySQL by user (main.py:83)
13:28:12.021 - INFO - Current user is user (main.py:407)
13:28:34.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:28:34.021 - INFO - Connected to MySQL by user (main.py:83)
13:28:34.021 - INFO - Current user is user (main.py:407)
13:29:43.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:29:43.021 - INFO - Connected to MySQL by user (main.py:83)
13:29:43.021 - INFO - Current user is user (main.py:407)
13:29:51.021 - INFO - user is log out (main.py:268)
13:30:18.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:30:18.021 - INFO - Connected to MySQL by user (main.py:83)
13:30:18.021 - INFO - Current user is user (main.py:407)
13:30:22.021 - INFO - user is log out (main.py:268)
13:30:39.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:30:39.021 - INFO - Connected to MySQL by user (main.py:83)
13:30:39.021 - INFO - Current user is user (main.py:407)
13:30:42.021 - INFO - user is log out (main.py:268)
13:30:47.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:30:47.021 - INFO - Connected to MySQL by user (main.py:83)
13:30:47.021 - INFO - Current user is user (main.py:407)
13:30:59.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:30:59.021 - INFO - Connected to MySQL by user (main.py:83)
13:30:59.021 - INFO - Current user is user (main.py:407)
13:31:03.021 - INFO - user is log out (main.py:268)
13:31:14.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:31:14.021 - INFO - Connected to MySQL by user (main.py:83)
13:31:14.021 - INFO - Current user is user (main.py:407)
13:31:29.021 - INFO - user is log out (main.py:268)
13:32:09.021 - ERROR - Not a Phone number entered (main.py:254)
13:32:10.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:32:10.021 - INFO - Connected to MySQL by user (main.py:83)
13:32:10.021 - INFO - Current user is user (main.py:407)
13:32:21.021 - INFO - user is log out (main.py:268)
13:32:30.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:32:30.021 - INFO - Connected to MySQL by user (main.py:83)
13:32:30.021 - INFO - Current user is user (main.py:407)
13:32:44.021 - ERROR - Not a Phone number entered (main.py:254)
13:32:45.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:32:45.021 - INFO - Connected to MySQL by user (main.py:83)
13:32:45.021 - INFO - Current user is user (main.py:407)
13:32:47.021 - INFO - user is log out (main.py:268)
13:32:51.021 - ERROR - Not a Phone number entered (main.py:254)
13:32:52.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:32:52.021 - INFO - Connected to MySQL by user (main.py:83)
13:32:52.021 - INFO - Current user is user (main.py:407)
13:32:54.021 - INFO - user is log out (main.py:268)
13:32:59.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:32:59.021 - INFO - Connected to MySQL by user (main.py:83)
13:32:59.021 - INFO - Current user is user (main.py:407)
13:33:04.021 - INFO - user is log out (main.py:268)
13:33:06.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:33:06.021 - INFO - Connected to MySQL by user (main.py:83)
13:33:06.021 - INFO - Current user is user (main.py:407)
13:33:11.021 - INFO - user is log out (main.py:268)
13:33:22.021 - ERROR - Not a Phone number entered (main.py:254)
13:33:23.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:33:23.021 - INFO - Connected to MySQL by user (main.py:83)
13:33:23.021 - INFO - Current user is user (main.py:407)
13:33:37.021 - INFO - user is log out (main.py:268)
13:33:44.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:33:44.021 - INFO - Connected to MySQL by user (main.py:83)
13:33:44.021 - INFO - Current user is user (main.py:407)
13:33:48.021 - INFO - user is log out (main.py:268)
13:33:56.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:33:56.021 - INFO - Connected to MySQL by user (main.py:83)
13:33:56.021 - INFO - Current user is user (main.py:407)
13:34:02.021 - INFO - user is log out (main.py:268)
13:34:09.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:34:09.021 - INFO - Connected to MySQL by user (main.py:83)
13:34:09.021 - INFO - Current user is user (main.py:407)
13:34:14.021 - INFO - user is log out (main.py:268)
13:34:19.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:34:19.021 - INFO - Connected to MySQL by user (main.py:83)
13:34:19.021 - INFO - Current user is user (main.py:407)
13:34:40.021 - INFO - user is log out (main.py:268)
13:34:41.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:34:41.021 - INFO - Connected to MySQL by user (main.py:83)
13:34:41.021 - INFO - Current user is user (main.py:407)
13:34:43.021 - INFO - user is log out (main.py:268)
13:34:44.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:34:44.021 - INFO - Connected to MySQL by user (main.py:83)
13:34:44.021 - INFO - Current user is user (main.py:407)
13:34:47.021 - INFO - user is log out (main.py:268)
13:35:04.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:35:04.021 - INFO - Connected to MySQL by user (main.py:83)
13:35:04.021 - INFO - Current user is user (main.py:407)
13:35:11.021 - INFO - user is log out (main.py:268)
13:35:28.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:35:28.021 - INFO - Connected to MySQL by user (main.py:83)
13:35:28.021 - INFO - Current user is user (main.py:407)
13:35:35.021 - INFO - user is log out (main.py:268)
13:35:44.021 - DEBUG - Number check returned: (1,) (main.py:20)
13:35:44.021 - INFO - Connected to MySQL by user (main.py:83)
13:35:44.021 - INFO - Current user is user (main.py:407)
13:37:17.021 - INFO - user is log out (main.py:268)
14:24:59.021 - DEBUG - Number check returned: (1,) (main.py:20)
14:24:59.021 - INFO - Connected to MySQL by user (main.py:83)
14:24:59.021 - INFO - Current user is user (main.py:407)
14:26:33.021 - INFO - user is log out (main.py:268)
14:26:36.021 - INFO - Connected to MySQL by admin (main.py:71)
14:26:36.021 - INFO - Current user is admin (main.py:311)
14:26:41.021 - INFO - admin is log out (main.py:268)
14:26:42.021 - INFO - Connected to MySQL by admin (main.py:71)
14:26:42.021 - INFO - Current user is admin (main.py:311)
14:26:46.021 - INFO - admin is log out (main.py:268)
14:26:47.021 - INFO - Connected to MySQL by admin (main.py:71)
14:26:47.021 - INFO - Current user is admin (main.py:311)
14:26:53.021 - INFO - admin is log out (main.py:268)
02:08:47.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:08:47.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:08:47.023 - INFO - Current user is user (AppClasses.py:73)
02:09:00.023 - INFO - user is log out (AppClasses.py:56)
02:09:01.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:09:01.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:09:01.023 - INFO - Current user is user (AppClasses.py:73)
02:09:31.023 - INFO - user is log out (AppClasses.py:56)
02:11:56.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:11:56.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:11:56.023 - INFO - Current user is user (AppClasses.py:73)
02:12:03.023 - INFO - Order added in table (AppClasses.py:279)
02:12:08.023 - INFO - user is log out (AppClasses.py:56)
02:12:20.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:12:20.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:12:20.023 - INFO - Current user is user (AppClasses.py:73)
02:12:25.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:25.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:25.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:26.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:30.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:30.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:31.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:31.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:31.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:32.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:33.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:34.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:35.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:35.023 - ERROR - Dialogue window already opened (AppClasses.py:86)
02:12:48.023 - INFO - user is log out (AppClasses.py:56)
02:13:14.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:13:14.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:13:14.023 - INFO - Current user is user (AppClasses.py:73)
02:13:17.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:17.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:18.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:18.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:20.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:20.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:30.023 - INFO - user is log out (AppClasses.py:56)
02:13:52.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:13:52.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:13:52.023 - INFO - Current user is user (AppClasses.py:73)
02:13:54.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:55.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:55.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:56.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:56.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:13:59.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:00.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:00.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:01.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:01.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:01.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:02.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:02.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:03.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:03.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:03.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:03.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:03.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:04.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:04.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:12.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:12.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:12.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:12.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:12.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:13.023 - WARNING - Dialogue window already opened (AppClasses.py:86)
02:14:17.023 - INFO - user is log out (AppClasses.py:56)
02:14:23.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:14:23.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:14:23.023 - INFO - Current user is user (AppClasses.py:73)
02:14:40.023 - INFO - user is log out (AppClasses.py:56)
02:14:46.023 - INFO - Connected to MySQL by admin (MySQLConnector.py:46)
02:14:46.023 - INFO - Current user is admin (AppClasses.py:73)
02:14:56.023 - INFO - admin is log out (AppClasses.py:56)
02:18:52.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:18:52.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:18:52.023 - INFO - Current user is user (AppClasses.py:73)
02:19:08.023 - INFO - Order deleted from table (AppClasses.py:317)
02:19:12.023 - INFO - Order deleted from table (AppClasses.py:317)
02:19:14.023 - ERROR - Failed to delete order (AppClasses.py:320)
02:19:23.023 - INFO - Order deleted from table (AppClasses.py:317)
02:19:30.023 - ERROR - 1217 (23000): Cannot delete or update a parent row: a foreign key constraint fails (MySQLConnector.py:106)
02:19:30.023 - ERROR - Failed to delete order (AppClasses.py:320)
02:19:51.023 - INFO - Order deleted from table (AppClasses.py:317)
02:19:55.023 - INFO - Order deleted from table (AppClasses.py:317)
02:19:58.023 - INFO - Order deleted from table (AppClasses.py:317)
02:20:00.023 - INFO - Order deleted from table (AppClasses.py:317)
02:20:02.023 - ERROR - 1217 (23000): Cannot delete or update a parent row: a foreign key constraint fails (MySQLConnector.py:106)
02:20:02.023 - ERROR - Failed to delete order (AppClasses.py:320)
02:21:01.023 - INFO - user is log out (AppClasses.py:56)
02:21:41.023 - ERROR - Not a Phone number entered (AppClasses.py:45)
02:21:42.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:21:42.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:21:42.023 - INFO - Current user is user (AppClasses.py:73)
02:21:48.023 - INFO - user is log out (AppClasses.py:56)
02:21:57.023 - ERROR - Not a Phone number entered (AppClasses.py:45)
02:21:57.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:21:57.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:21:57.023 - INFO - Current user is user (AppClasses.py:73)
02:22:00.023 - INFO - user is log out (AppClasses.py:56)
02:27:36.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:27:36.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:27:36.023 - INFO - Current user is user (AppClasses.py:73)
02:27:47.023 - INFO - user is log out (AppClasses.py:56)
02:28:52.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:28:52.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:28:52.023 - INFO - Current user is user (AppClasses.py:73)
02:28:59.023 - INFO - user is log out (AppClasses.py:56)
02:29:44.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:29:44.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:29:44.023 - INFO - Current user is user (AppClasses.py:73)
02:30:26.023 - INFO - user is log out (AppClasses.py:56)
02:30:51.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:30:51.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:30:51.023 - INFO - Current user is user (AppClasses.py:73)
02:31:48.023 - INFO - user is log out (AppClasses.py:56)
02:32:03.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:32:03.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:32:03.023 - INFO - Current user is user (AppClasses.py:73)
02:32:06.023 - INFO - user is log out (AppClasses.py:56)
02:32:13.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:32:13.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:32:13.023 - INFO - Current user is user (AppClasses.py:73)
02:32:17.023 - INFO - user is log out (AppClasses.py:56)
02:32:22.023 - ERROR - Not a Phone number entered (AppClasses.py:45)
02:32:23.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:32:23.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:32:23.023 - INFO - Current user is user (AppClasses.py:73)
02:32:25.023 - INFO - user is log out (AppClasses.py:56)
02:32:31.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:32:31.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:32:31.023 - INFO - Current user is user (AppClasses.py:73)
02:32:34.023 - INFO - user is log out (AppClasses.py:56)
02:32:43.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
02:32:43.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
02:32:43.023 - INFO - Current user is user (AppClasses.py:73)
02:32:49.023 - INFO - user is log out (AppClasses.py:56)
03:13:47.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:13:47.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:13:47.023 - INFO - Current user is user (AppClasses.py:73)
03:16:20.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:16:20.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:16:20.023 - INFO - Current user is user (AppClasses.py:73)
03:23:41.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:23:41.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:23:41.023 - INFO - Current user is user (AppClasses.py:70)
03:24:50.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:24:50.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:24:50.023 - INFO - Current user is user (AppClasses.py:70)
03:24:53.023 - INFO - user is log out (AppClasses.py:53)
03:25:01.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:25:01.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:25:01.023 - INFO - Current user is user (AppClasses.py:70)
03:25:04.023 - INFO - user is log out (AppClasses.py:53)
03:25:11.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:25:11.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:25:11.023 - INFO - Current user is user (AppClasses.py:70)
03:25:16.023 - INFO - user is log out (AppClasses.py:53)
03:25:22.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:25:22.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:25:22.023 - INFO - Current user is user (AppClasses.py:70)
03:25:35.023 - INFO - user is log out (AppClasses.py:53)
03:25:39.023 - INFO - Connected to MySQL by admin (MySQLConnector.py:46)
03:25:39.023 - INFO - Current user is admin (AppClasses.py:70)
03:25:44.023 - INFO - admin is log out (AppClasses.py:53)
03:29:20.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:29:21.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:29:21.023 - INFO - Current user is user (AppClasses.py:73)
03:35:25.023 - ERROR - Not a Phone number entered (AppClasses.py:52)
03:35:34.023 - DEBUG - Number check returned: None (MySQLConnector.py:17)
03:35:34.023 - ERROR - Invalid phone number (MySQLConnector.py:60)
03:35:34.023 - ERROR - Invalid phone number (AppClasses.py:45)
03:35:49.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:35:49.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:35:49.023 - INFO - Current user is user (AppClasses.py:84)
03:36:07.023 - INFO - user is log out (AppClasses.py:67)
03:36:09.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:36:09.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:36:09.023 - INFO - Current user is user (AppClasses.py:84)
03:36:12.023 - INFO - user is log out (AppClasses.py:67)
03:36:13.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:36:13.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:36:13.023 - INFO - Current user is user (AppClasses.py:84)
03:36:15.023 - ERROR - Error checking id (RegexChecker.py:24)
03:36:15.023 - ERROR - Order id entered is invalid (AppClasses.py:355)
03:36:16.023 - ERROR - Error checking id (RegexChecker.py:24)
03:36:16.023 - ERROR - Order id entered is invalid (AppClasses.py:355)
03:36:16.023 - ERROR - Error checking id (RegexChecker.py:24)
03:36:16.023 - ERROR - Order id entered is invalid (AppClasses.py:355)
03:36:20.023 - INFO - user is log out (AppClasses.py:67)
03:36:24.023 - INFO - Current user is None (AppClasses.py:84)
03:36:32.023 - INFO - None is log out (AppClasses.py:67)
03:36:39.023 - ERROR - Not a Phone number entered (AppClasses.py:52)
03:36:52.023 - DEBUG - Number check returned: (1,) (MySQLConnector.py:17)
03:36:52.023 - INFO - Connected to MySQL by user (MySQLConnector.py:58)
03:36:52.023 - INFO - Current user is user (AppClasses.py:84)
03:36:57.023 - INFO - user is log out (AppClasses.py:67)
